### ISSUE TITLE
Getting NoClassDefFoundError when building project with intelliJ

### ISSUE THREAD

**Issue by liuzhen2008** [sksamuel/sbt-scapegoat#104]
Getting the error stack below.

What should I do? This project is known to work in a linux environment, i just setup my scala environment on windows and trying to build it. Bumping into this error when I click on "build" on intelliJ
```
Error:scalac: Error: scala/xml/MetaData
java.lang.NoClassDefFoundError: scala/xml/MetaData
	at com.sksamuel.scapegoat.io.IOUtils$.writeXMLReport(IOUtils.scala:29)
	at com.sksamuel.scapegoat.ScapegoatComponent$$anon$1.run(plugin.scala:179)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1446)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1430)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1423)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1539)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
	at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:42)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:43)
	at org.jetbrains.jps.incremental.scala.remote.Main$.compileLogic(Main.scala:117)
	at org.jetbrains.jps.incremental.scala.remote.Main$.handleCommand(Main.scala:109)
	at org.jetbrains.jps.incremental.scala.remote.Main$.serverLogic(Main.scala:95)
	at org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:53)
	at org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
	at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
```

**Comment by liuzhen2008** [comment]
i notice if i do the usual mvn package it still works. Something to do with the way intelliJ does "build module" that seems to be missing something.
